name = "testforum"
type = "javascript"
workers_dev = true
# Add your account ID here
#account_id = ""

[build.upload]
format = "modules"
dir = "src"
main = "./main.mjs"
rules = [{type = "Data", globs = ["**/*.html"]}]

[durable_objects]
bindings = [
	{ name = "threaddb", class_name = "ThreadDB"}
]
